# Train config ---------------------------------------
log_level: logging.INFO
seed: 0
deterministic: True
cudnn_benchmark: True # Use cudnn 
resume_from: "../checkpoints/vitpose-h-coco_25.pth" # CKPT path
total_epochs: 5
dataset: "doodle"
# resume_from: False
gpu_ids: []
launcher: 'none' # When distributed training ['none', 'pytorch', 'slurm', 'mpi']
use_amp: True
validate: True
autoscale_lr: False
enable_wandb: True
resume_keypoint_head_weight: False
dist_params: 
  ...
