base:
  url: "https://drive.google.com/file/d/13oBl5MTVcWER3YU4fSxW3ATlVfueFQPY/view?usp=share_link"
  md5: "d692e3dd5fa1b9658949d452bebf1cda"
  ckpt_name: "ckpt_base.pth"
  http_proxy: NULL
  base_size: [1024, 1024]

fast:
  url: "https://drive.google.com/file/d/1iRX-0MVbUjvAVns5MtVdng6CQlGOIo3m/view?usp=share_link"
  md5: "9efdbfbcc49b79ef0f7891c83d2fd52f"
  ckpt_name: "ckpt_fast.pth"
  http_proxy: NULL
  base_size: [384, 384]

base-nightly:
  url: "https://github.com/plemeri/transparent-background/releases/download/1.2.10/ckpt_base_nightly.pth"
  md5: NULL
  ckpt_name: "ckpt_base_nightly.pth"
  http_proxy: NULL
  base_size: [1024, 1024]
